-- Run this once in the Supabase SQL editor to create the table backing
-- the site-wide feedback widget (api/feedback.js, admin-feedback.html).

create table if not exists site_feedback (
  id bigint generated by default as identity primary key,
  message text not null,
  page text,
  created_at timestamptz not null default now()
);

-- All reads/writes go through /api/feedback.js using the service role key,
-- which bypasses RLS, so enabling RLS with no policies locks the table
-- down from direct anon access via the Supabase client.
alter table site_feedback enable row level security;
